# Generated by Django 4.0.4 on 2022-05-17 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostExperiencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='logo',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
