# Generated by Django 4.0.4 on 2022-05-18 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostExperiencia', '0004_bio_skills_alter_post_body_alter_post_cargo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bio',
            options={'verbose_name': 'Biografía', 'verbose_name_plural': 'Biografía'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Experiencia Laboral', 'verbose_name_plural': 'Experiencia Laboral'},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name_plural': 'Habilidades'},
        ),
        migrations.AlterField(
            model_name='post',
            name='final',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de finalización'),
        ),
        migrations.AlterField(
            model_name='post',
            name='inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio'),
        ),
    ]
