# Generated by Django 4.0.4 on 2022-05-19 02:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostExperiencia', '0005_alter_bio_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name='Descripción del puesto'),
        ),
    ]
