# Generated by Django 4.0.4 on 2022-05-19 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostExperiencia', '0006_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='linkEmpresa',
            field=models.URLField(blank=True, null=True, verbose_name='Link de la empresa'),
        ),
    ]
