# Generated by Django 4.0.4 on 2022-05-19 03:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostExperiencia', '0008_alter_bio_nacionalidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='bio',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Biografía'),
            preserve_default=False,
        ),
    ]
